import 'dart:async';
import 'package:floor/floor.dart';
import 'package:sqflite/sqflite.dart' as sqflite;

import '../../dtos/category_dto.dart';
import '../daos/category_dao.dart';


// This is generated by the floor generator
part 'all4u_db.g.dart';

@Database(version: 1, entities: [CategoryDTO])
abstract class All4UDb extends FloorDatabase {
  CategoryDAO get categoryDAO;
}